version: '3.7'
services:    
    web:
        image: makechat
        build: .
        command: node app.js
        ports: 
            - "4040:4040"
        volumes: 
            - ./makechat/app
            - /app/node_modules
        depends_on:
            - mongodb
    mongodb:
        image: "mongo"
        ports:
            - "27017:27017"